server:
  port: 8888

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@58.234.223.222:1521:xe
    username: C##GREENOLIVES
    password: green123123
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\DEV\04_project\Green-Olives\cocktable-boot
    web:
      resources:
        static-locations: classpath:/productImages/

  ## jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        format_sql: 'true'
        hql:
          bulk_id_strategy: 'org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy'

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

image:

  add-resource-locations: classpath:/static/productImages/
  add-resource-handler: /productImages/**

  image-dir: src/main/resources/static/productImages
  image-url: http://localhost:8888/productImages/

# Logging Level
logging:
  level:
    root: info